const DEVICE_NAME = 'FOOTCAR_RCTRL';
const SERVICE_UUID_RCTRL = 0x00f3;

const CHAR_UUID_SERVO = 0xff01;
const CHAR_UUID_MOTOR_A = 0xff02;
const CHAR_UUID_MOTOR_B = 0xff03;

export {
  DEVICE_NAME,
  SERVICE_UUID_RCTRL,
  CHAR_UUID_SERVO,
  CHAR_UUID_MOTOR_A,
  CHAR_UUID_MOTOR_B,
};
